# Generated by Django 6.0.1 on 2026-01-22 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedip',
            name='user_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('U', 'COMMON_USER'), ('G', 'GUIDE'), ('A', 'ADMIN'), ('C', 'TOUR_COMPANY')], default='U', max_length=1, verbose_name='User Type'),
        ),
    ]
